fix dependencies
litmuschaos/litmusctl pull request #191
Opened 2024-02-04 13:41 UTC by kartikaysaxena

Fixes #190

2024-02-04 21:39 UTC, kartikaysaxena commented on pkg/utils/experiment.go
> -
Removed it because the lint was complaining about unused helper function

2024-02-04 21:40 UTC, kartikaysaxena commented on pkg/utils/experiment.go
> +	randomGenerator := rand.New(source)
Changed because rand.Seed is depreciated as of now.

2024-02-04 21:42 UTC, kartikaysaxena commented on pkg/apis/infrastructure/infra.go
> +	bodyBytes, err := io.ReadAll(resp.Body)
ioutil is deprecated in favour of io and os

2024-02-04 21:45 UTC, kartikaysaxena commented
<img width="1440" alt="Screenshot 2024-02-05 at 3 14 42 AM" src="https://github.com/litmuschaos/litmusctl/assets/120778728/1e6a8b67-c058-48f3-a73a-dfac47b326e1">
Now all warnings seems to be resolved.

2024-02-05 04:35 UTC, neelanjan00 approved these changes

2024-02-06 15:40 UTC, Nageshbansal commented on pkg/apis/environment/environment.go
> +	query, _ := json.Marshal(gqlReq)
instead of replacing it with '_' , it will be better to have a not nil err check here.

2024-02-06 15:40 UTC, Nageshbansal commented on pkg/apis/infrastructure/infra.go
> +	query, _ := json.Marshal(gqlReq)
add a not nil err check here

2024-02-07 04:50 UTC, Jonsy13 approved these changes

2024-02-12 06:55 UTC, SarthakJain26 approved these changes

2024-02-12 06:55 UTC, SarthakJain26 commented
@deep-poharkar @Nageshbansal please review this PR

2024-02-12 06:59 UTC, Nageshbansal commented
Lgtm 🚀

2024-02-12 09:59 UTC, deep-poharkar commented
looks good

2024-02-15 06:26 UTC, SarthakJain26 commented
@kartikaysaxena can you please try to resolve the merge conflicts, we can take this PR in litmusctl 1.3.0 release

2024-02-15 09:39 UTC, kartikaysaxena commented
Hey @SarthakJain26, both my commits are signed off, and DCO is passing, but it is still showing that merging is blocked. Can you help with that?

2024-02-15 09:42 UTC, SarthakJain26 commented
It's because the build pipeline is failing, here are the logs: 
<img width="1300" alt="Screenshot 2024-02-15 at 3 12 11 PM" src="https://github.com/litmuschaos/litmusctl/assets/45846277/286d30fa-3a41-49c9-b4f1-06878470198f">

2024-02-15 10:30 UTC, SarthakJain26 commented
@kartikaysaxena looks like there's one merge conflict, can you try resolving that as well please

2024-02-15 10:45 UTC, SarthakJain26 requested changes

2024-02-15 10:45 UTC, SarthakJain26 commented on pkg/apis/infrastructure/infra.go
> -func GetServerVersion(endpoint string) (ServerVersionResponse, error) {
Please add back this function, looks like it was deleted while resolving the conflicts

2024-02-15 11:17 UTC, SarthakJain26 approved these changes

2024-02-15 11:18 UTC, merged

2024-02-15 11:18 UTC, SarthakJain26 commented
Thanks @kartikaysaxena for fixing this 🚀