fix: added missing environmentID flag
litmuschaos/litmusctl pull request #198
Opened 2024-02-14 11:47 UTC by kartikaysaxena

Should fix #197

2024-02-14 11:50 UTC, kartikaysaxena commented
The flag had been implemented earlier [here](https://github.com/litmuschaos/litmusctl/blob/master/pkg/cmd/connect/infra.go#L108), just the flag parser was missing, I have added that.

2024-02-14 13:15 UTC, neelanjan00 approved these changes

2024-02-15 06:18 UTC, SarthakJain26 commented
@kartikaysaxena can you please update the flag to environment-id, since this is the casing that we are following. Also please update the example command in connect/connect.go by adding the environment-id flag.

2024-02-15 10:54 UTC, kartikaysaxena commented
> @kartikaysaxena can you please update the flag to environment-id, since this is the casing that we are following. Also please update the example command in connect/connect.go by adding the environment-id flag.

Sure will do it.

2024-02-15 11:54 UTC, SarthakJain26 requested changes

2024-02-15 11:54 UTC, SarthakJain26 commented on pkg/cmd/connect/connect.go
> +		litmusctl connect chaos-infra --name="new-chaos-infra" --non-interactive --environment-id="my-environment-id"
No need to add incase of interactive mode, user will see a prompt to enter the environment-id incase of interactive mode

2024-02-15 12:20 UTC, SarthakJain26 approved these changes

2024-02-15 12:20 UTC, merged