Merge get/list env command
litmuschaos/litmusctl pull request #206
Opened 2024-03-07 14:27 UTC by shivam-Purohit

Merges both `get chaos-environment` and `list chaos-envrionments` commands into a single command as` get chaos-environments`.

2024-03-07 14:29 UTC, shivam-Purohit commented
@SarthakJain26 its hard to just add a flag and show the whole details. Like not hard but unnecessary cause it will make the command slower if we query all the fields for list environments also. We should consider adding it to descibe or something. WDYT?

2024-03-08 05:40 UTC, shivam-Purohit commented
i havent touched other part of the code which can be optimised with this new get environment endpoint, we would do that in some other pr. I will create an issue regarding that.

2024-03-08 05:42 UTC, shivam-Purohit commented
```
/litmusctl get chaos-environments --project-id="8adf62d5-64f8-4c66-ab53-63729db9dd9a" --environment-id="shivamenv"

CHAOS ENVIRONMENT DETAILS

CHAOS ENVIRONMENT ID	 shivamenv

CHAOS ENVIRONMENT NAME	 shivamenv

CHAOS ENVIRONMENT Type	 NON_PROD

CREATED AT		 55908-04-03 16:42:51 +0530 IST

CREATED BY		 admin

UPDATED AT		 55908-04-03 16:42:51 +0530 IST

UPDATED BY		 admin

CHAOS INFRA IDs	 d99c7d14-56ef-4836-8537-423f28ceac4e

TAGS	
```
```
./litmusctl get chaos-environments --project-id="8adf62d5-64f8-4c66-ab53-63729db9dd9a"

CHAOS ENVIRONMENT ID	CHAOS ENVIRONMENT NAME		CREATED AT			CREATED BY

shivamnewenv		shivamnewenv			55962-10-01 15:05:45 +0530 IST	admin

newenvironmenttest	newenvironmenttest		55912-12-01 10:55:23 +0530 IST	admin

shivamenv		shivamenv			55908-04-03 16:42:51 +0530 IST	admin

Press Enter to show more environments (or type 'q' to quit): q
```

2024-03-14 03:15 UTC, Nageshbansal requested changes

2024-03-14 03:15 UTC, Nageshbansal commented on pkg/cmd/get/environments.go
> +		environmentList, err := environment.ListChaosEnvironments(projectID, credentials)
Shouldn't we have a check here to see if `environmentID` is given or not before sending the query

2024-03-14 03:15 UTC, Nageshbansal commented on pkg/cmd/get/get.go
> +		litmusctl get chaos-experiments --project-id=""
add example for environment-id also

2024-03-15 12:15 UTC, shivam-Purohit commented
@Nageshbansal does the master branch have updated-dependencies? Not rebase in case, dont want to add extra commit

2024-04-12 11:21 UTC, SarthakJain26 approved these changes

2024-04-12 11:26 UTC, Nageshbansal approved these changes
LGTM, geat work 🚀

2024-04-15 06:51 UTC, merged