Added compatibility matrix and API to fetch GQL server version
litmuschaos/litmusctl pull request #84
Opened 2022-08-08 07:48 UTC by Saranya-jena

Added compatibility matrix and API to fetch GQL server version

2022-08-08 08:01 UTC, SarthakJain26 requested changes

2022-08-08 12:35 UTC, SarthakJain26 commented on pkg/cmd/config/setAccount.go
> +					utils.White_B.Println("")
Is this required?

2022-08-08 12:35 UTC, SarthakJain26 commented on pkg/cmd/version/version.go
> +		utils.White_B.Println("")
Same

2022-08-08 12:35 UTC, SarthakJain26 commented on pkg/cmd/config/setAccount.go
> +					utils.White_B.Println("")
Instead can we have `utils.White_B.Print("]\n")`

2022-08-08 13:25 UTC, SarthakJain26 approved these changes

2022-08-08 14:18 UTC, Jonsy13 commented on pkg/cmd/config/setAccount.go
> +						isCompatible = true
we can add a `break` also here

2022-08-09 04:48 UTC, Jonsy13 approved these changes

2022-08-09 06:30 UTC, imrajdas approved these changes

2022-08-09 06:30 UTC, merged